import path from 'node:path';
import os from 'node:os';
import {readJSON,atomicJSON} from './manifest.mjs';
export const privateRoot=path.join(os.homedir(),'.codex','video-bot');
export const configFile=process.env.VIDEO_BOT_CONFIG??path.join(privateRoot,'config.json');
export const defaults={sheetId:'1MJU-AxH_7dTMcOdi3CM0QkWusT03lSlsWT1qL37ceVw',sheetTab:'Trang tính1',driveFolderId:'13wJbXO3Y6SPNi3iH3JDLBokkb900Je-v',jobRoot:'D:/remotion/tasks/video-bot/jobs',resourceRoot:'D:/remotion',ttsRoot:'D:/viet tts/VieNeu-TTS',secretsFile:path.join(privateRoot,'secrets.json'),googleCredentials:path.join(privateRoot,'google.json'),workerId:os.hostname(),pollMs:5000,heartbeatMs:25000,geminiImageModel:'gemini-3.1-flash-lite-image',maxImagesPerVideo:16,skills:{'viet-tiktok-story-video':'C:/Users/ADMIN/.codex/skills/viet-tiktok-story-video/SKILL.md','drama-mascot-video':'C:/Users/ADMIN/.gemini/config/skills/drama-mascot-video/SKILL.md'},channels:[]};
export async function loadConfig({secrets=true}={}){const c={...defaults,...await readJSON(configFile,{})};if(secrets)c.secrets=await readJSON(c.secretsFile,{});return c;}
export async function saveConfig(value){const allowed=['cloudUrl','jobRoot','resourceRoot','ttsRoot','googleCredentials','googleClientFile','workerId','mediaRelayTemplate','codexNode','codexScript','channels','geminiImageModel','maxImagesPerVideo'];if(Object.keys(value).some(k=>!allowed.includes(k)))throw new Error('Trường cấu hình không hỗ trợ');if(value.cloudUrl&&new URL(value.cloudUrl).protocol!=='https:')throw new Error('Cloud URL phải HTTPS');await atomicJSON(configFile,{...await readJSON(configFile,{}),...value});}
export function requireConnections(config){const missing=[];if(!config.cloudUrl)missing.push('Cloud URL');if(!config.secrets?.runnerToken)missing.push('Runner token trong secrets.json');if(!config.googleCredentials)missing.push('Google credentials');if(missing.length)throw new Error(`Thiếu kết nối: ${missing.join(', ')}`);}
