import {realpath,stat,readFile} from 'node:fs/promises';
import path from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
const run=promisify(execFile);
export async function confined(root,file){const [base,target]=await Promise.all([realpath(root),realpath(path.resolve(root,file))]);const relative=path.relative(base,target);if(relative.startsWith('..')||path.isAbsolute(relative)||!relative)throw new Error('Artifact ngoài thư mục job');return target;}
export function validateResult(result){if(!result||!['ready_for_upload','needs_input','failed'].includes(result.status)||typeof result.message!=='string'||typeof result.videoPath!=='string'||typeof result.caption!=='string'||typeof result.qualityReportPath!=='string'||!Array.isArray(result.hashtags)||result.hashtags.some(x=>typeof x!=='string'))throw new Error('Agent result sai schema');if(result.status!=='ready_for_upload')throw new Error(`Cần đầu vào: ${result.message}`);if(!result.caption.trim())throw new Error('Thiếu caption');}
export function validateProbe(probe){const video=probe.streams?.find(s=>s.codec_type==='video'),audio=probe.streams?.find(s=>s.codec_type==='audio');if(video?.codec_name!=='h264'||audio?.codec_name!=='aac'||!audio.channels||Math.abs(video.width/video.height-9/16)>0.002||!(Number(probe.format?.duration)>0))throw new Error('MP4 phải H.264/AAC 9:16, có audio và thời lượng');}
export async function verifyMedia(root,result,{probe=async file=>JSON.parse((await run('ffprobe',['-v','error','-show_streams','-show_format','-of','json',file],{windowsHide:true})).stdout)}={}){validateResult(result);const videoPath=await confined(root,result.videoPath);if(path.extname(videoPath).toLowerCase()!=='.mp4'||(await stat(videoPath)).size<1024)throw new Error('Thiếu MP4 thật');const qualityPath=await confined(root,result.qualityReportPath);const quality=JSON.parse(await readFile(qualityPath,'utf8'));if(quality.passed!==true||!Array.isArray(quality.checks)||!quality.checks.length||quality.checks.some(c=>!c.name||c.passed!==true||typeof c.evidence!=='string'||!c.evidence.trim()))throw new Error('Thiếu bằng chứng cổng chất lượng');for(const required of ['visual','audio','captions','skill'])if(!quality.checks.some(c=>c.name===required))throw new Error(`Thiếu kiểm tra ${required}`);validateProbe(await probe(videoPath));return {videoPath,qualityPath};}
export async function verifyPublicMP4(url,{fetchImpl=fetch}={}){const u=new URL(url);if(u.protocol!=='https:'||u.username||u.password)throw new Error('Media URL phải HTTPS công khai');const response=await fetchImpl(u,{headers:{Range:'bytes=0-4095'},signal:AbortSignal.timeout(20000),redirect:'error'});if(![200,206].includes(response.status)||!/^video\/mp4\b/i.test(response.headers.get('content-type')??''))throw new Error('Media URL không phục vụ MP4 công khai');const reader=response.body.getReader();const {value}=await reader.read();await reader.cancel();if(!value||!Buffer.from(value).includes(Buffer.from('ftyp')))throw new Error('Media URL thiếu MP4 signature');return url;}
